---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/rhpds/code-red-breach-challenge-hacker-app
    app.quarkus.io/quarkus-version: 3.27.2.redhat-00001
    app.quarkus.io/commit-id: 5c1e821a641e93830b186419a808752a94c98ac2
    app.quarkus.io/vcs-uri: https://github.com/rhpds/code-red-breach-challenge-hacker-app.git
    app.quarkus.io/build-timestamp: 2026-03-16 - 11:52:18 +0000
  labels:
    app.kubernetes.io/name: hackerapp
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: hackerapp
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8092
  selector:
    app.kubernetes.io/name: hackerapp
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app.kubernetes.io/name: hackerapp
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: s2i-java
spec:
  dockerImageRepository: fabric8/s2i-java
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/rhpds/code-red-breach-challenge-hacker-app
    app.quarkus.io/quarkus-version: 3.27.2.redhat-00001
    app.quarkus.io/commit-id: 5c1e821a641e93830b186419a808752a94c98ac2
    app.quarkus.io/vcs-uri: https://github.com/rhpds/code-red-breach-challenge-hacker-app.git
    app.quarkus.io/build-timestamp: 2026-03-16 - 11:52:18 +0000
  labels:
    app.kubernetes.io/name: hackerapp
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: hackerapp
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/rhpds/code-red-breach-challenge-hacker-app
    app.quarkus.io/quarkus-version: 3.27.2.redhat-00001
    app.quarkus.io/commit-id: 5c1e821a641e93830b186419a808752a94c98ac2
    app.quarkus.io/vcs-uri: https://github.com/rhpds/code-red-breach-challenge-hacker-app.git
    app.quarkus.io/build-timestamp: 2026-03-16 - 11:52:18 +0000
  labels:
    app.kubernetes.io/name: hackerapp
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: hackerapp
spec:
  output:
    to:
      kind: ImageStreamTag
      name: hackerapp:1.0-SNAPSHOT
  source:
    binary: {}
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-java:2.3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/rhpds/code-red-breach-challenge-hacker-app
    app.quarkus.io/quarkus-version: 3.27.2.redhat-00001
    app.quarkus.io/commit-id: 5c1e821a641e93830b186419a808752a94c98ac2
    app.quarkus.io/vcs-uri: https://github.com/rhpds/code-red-breach-challenge-hacker-app.git
    app.quarkus.io/build-timestamp: 2026-03-16 - 11:52:18 +0000
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/name: hackerapp
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: hackerapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hackerapp
      app.kubernetes.io/version: 1.0-SNAPSHOT
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
        app.openshift.io/vcs-uri: https://github.com/rhpds/code-red-breach-challenge-hacker-app
        app.quarkus.io/quarkus-version: 3.27.2.redhat-00001
        app.quarkus.io/commit-id: 5c1e821a641e93830b186419a808752a94c98ac2
        app.quarkus.io/vcs-uri: https://github.com/rhpds/code-red-breach-challenge-hacker-app.git
        app.quarkus.io/build-timestamp: 2026-03-16 - 11:52:18 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/name: hackerapp
        app.kubernetes.io/version: 1.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: hackerapp:1.0-SNAPSHOT
          imagePullPolicy: Always
          name: hackerapp
          ports:
            - containerPort: 8092
              name: http
              protocol: TCP
